services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"

    volumes:
      - ./ai/files:/ai/files

    command: ["npm", "run", "dev"]

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - python-service
    command: ["npm", "start"]

  python-service:
    build: ./ai
    ports:
      - "5001:5001"

    command: ["python", "main.py"]

  