version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - rabbitmq

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mysql:
    build: ./repository
    ports:
      - "3306:3306"
    volumes:
      - ./repository:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: latteforte
      MYSQL_DATABASE: assistente

  rabbitmq:
    image: "rabbitmq:latest"
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mysql_data: